syntax                     = "Luau"
column_width               = 120
line_endings               = "Unix"
indent_type                = "Tabs"
indent_width               = 4
quote_style                = "AutoPreferDouble"
call_parentheses           = "Input"
space_after_function_names = "Never"

[sort_requires]
enabled = true
# Group consecutive require statements into a single "block", and then
# requires are sorted only within that block. Blocks of requires do
# not move around the file.
